### ISSUE TITLE
Cannot find module 'shelljs/global

### ISSUE THREAD

**Issue by mikeerickson** [nfischer/shelljs-transpiler#24]

**Comment by mikeerickson** [comment]
Sorry, didn't mean to submit... When running any transpiled script, I receive the error outlined below.  I have confirmed that `shelljs` is installed globally


The following portion

```
#!/usr/bin/env node
require('shelljs/global');
```

throws the following error

```
 $ node sass-lint.js
module.js:341
    throw err;
    ^

Error: Cannot find module 'shelljs/global'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/mikeerickson/Cirrus-Insight-Gmail-UI/sandbox/scripts/sass-lint.js:2:1)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
```

**Comment by nfischer** [comment]
@mikeerickson Could you provide the output of these commands?

```bash
$ npm config get prefix
$ echo $NODE_PATH
```

Your NODE_PATH should be something like `$(npm config get prefix)/lib/node_modules`.

Although, I personally recommend installing ShellJS as a local dependency in your `~/bin/` folder where you keep your scripts, since I think that'll be easier to manage all around. So that would be `cd ~/bin/ && npm install shelljs`.

**Comment by mikeerickson** [comment]
```
$ npm config get prefix

==> usr/local

echo $NODE_PATH

==> returns a blank value (no result)
```

However, I have since taken your advise and install local to the project where the scripts are saved.
